In [2]:
import numpy as np

m=np.random.randint(1,20,size=20).reshape(4,5)
a=m.max()
b=m.min()

nm= (m - b)/(a-b)
print("Max of normalised : ",nm.max())
print("Min of normalised : ",nm.min())
print("Normalised matrix = ",nm)

Max of normalised :  1.0
Min of normalised :  0.0
Normalised matrix =  [[0.29411765 0.64705882 0.17647059 0.76470588 1.        ]
 [0.05882353 0.05882353 1.         0.52941176 0.52941176]
 [0.29411765 0.23529412 0.         0.94117647 0.29411765]
 [1.         0.76470588 0.64705882 0.35294118 0.        ]]


In [3]:
x=np.zeros((8,8), dtype=int)
x[0::2,1::2]=1
x[1::2,0::2]=1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [4]:
np.random.randint(1,10,size=10)

array([8, 6, 8, 1, 2, 1, 7, 5, 2, 7], dtype=int32)

In [5]:
a=np.arange(20, dtype=float)
nans=np.random.choice(np.arange(20), size= 5 ,replace=False)

a[nans]=np.nan
print("\nThe Array with nan values : ",a)
mask=np.isnan(a)
clean=np.nanmean(a)
a[mask]=clean

print("\nThe Array without nan values : ",a)


The Array with nan values :  [nan  1.  2. nan nan  5.  6.  7.  8.  9. nan nan 12. 13. 14. 15. 16. 17.
 18. 19.]

The Array without nan values :  [10.8  1.   2.  10.8 10.8  5.   6.   7.   8.   9.  10.8 10.8 12.  13.
 14.  15.  16.  17.  18.  19. ]


In [24]:
x=np.random.randint(0,100,size=50)
mean=np.mean(x)
std_dev=np.std(x)

z=(x-mean)/std_dev

print("The mean and std.dev before transformation : ",mean," ,",std_dev)
print("The mean and std.dev after transformation : ",np.mean(z).round(6)," ,",np.std(z).round(6))


The mean and std.dev before transformation :  55.94  , 26.313046193856007
The mean and std.dev after transformation :  0.0  , 1.0


In [35]:
arr=np.append(np.random.randint(0,100,100),[456,-360])
Q1=np.percentile(arr,25)
Q3=np.percentile(arr,75)
IQR=Q3-Q1

LB=Q1-1.5*IQR
UB=Q3+1.5*IQR

Outlier_indices=np.where((arr<LB)|(arr>UB))[0]

print("Q1 : ",Q1,"Q3 : ",Q3,"IQR : ",IQR)
print("Upper Bound : ",UB ,"&","Lower Bound : ",LB)
print("Outliers : ", Outlier_indices)
print("Outlier Values : ",arr[Outlier_indices])

Q1 :  26.25 Q3 :  77.0 IQR :  50.75
Upper Bound :  153.125 & Lower Bound :  -49.875
Outliers :  [100 101]
Outlier Values :  [ 456 -360]
