In [1]:
import numpy as np

m=np.random.randint(1,20,size=20).reshape(4,5)
a=m.max()
b=m.min()

nm= (m - b)/(a-b)
print("Max of normalised : ",nm.max())
print("Min of normalised : ",nm.min())
print("Normalised matrix = ",nm)

Max of normalised :  1.0
Min of normalised :  0.0
Normalised matrix =  [[0.16666667 0.38888889 0.         0.38888889 0.16666667]
 [0.44444444 0.66666667 0.83333333 0.83333333 1.        ]
 [0.05555556 0.88888889 0.77777778 0.33333333 0.22222222]
 [0.88888889 0.05555556 0.66666667 0.61111111 0.27777778]]


In [2]:
x=np.zeros((8,8), dtype=int)
x[0::2,1::2]=1
x[1::2,0::2]=1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [3]:
np.random.randint(1,10,size=10)

array([7, 2, 4, 6, 6, 3, 3, 3, 7, 1], dtype=int32)

In [4]:
a=np.arange(20, dtype=float)
nans=np.random.choice(np.arange(20), size= 5 ,replace=False)

a[nans]=np.nan
print("\nThe Array with nan values : ",a)
mask=np.isnan(a)
clean=np.nanmean(a)
a[mask]=clean

print("\nThe Array without nan values : ",a)


The Array with nan values :  [nan  1.  2.  3.  4.  5.  6.  7.  8.  9. nan 11. 12. nan nan 15. 16. 17.
 nan 19.]

The Array without nan values :  [ 9.  1.  2.  3.  4.  5.  6.  7.  8.  9.  9. 11. 12.  9.  9. 15. 16. 17.
  9. 19.]
